-- MySQL Script generated by MySQL Workbench
-- Sat May  2 18:56:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PropositionVoter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PropositionVoter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PropositionVoter` DEFAULT CHARACTER SET utf8 ;
USE `PropositionVoter` ;

-- -----------------------------------------------------
-- Table `PropositionVoter`.`Proposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PropositionVoter`.`Proposition` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CreationDate` DATETIME NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Content` NVARCHAR(500) NOT NULL,
  `CreatedByUserID` INT NOT NULL,
  `ClosedDate` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PropositionVoter`.`Discussion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PropositionVoter`.`Discussion` (
  `ID` INT NOT NULL,
  `UserID` VARCHAR(45) NOT NULL,
  `Content` VARCHAR(250) NOT NULL,
  `PropositionID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Discussion_Proposition_idx` (`PropositionID` ASC) VISIBLE,
  CONSTRAINT `fk_Discussion_Proposition`
    FOREIGN KEY (`PropositionID`)
    REFERENCES `PropositionVoter`.`Proposition` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PropositionVoter`.`User_Proposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PropositionVoter`.`User_Proposition` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PropositionID` INT NOT NULL,
  `VotedFor` TINYINT NOT NULL,
  `VoteDate` DATETIME NOT NULL,
  `Comment` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idUser_Voted_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_User_Proposition_Proposition_idx` (`PropositionID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Proposition_Proposition`
    FOREIGN KEY (`PropositionID`)
    REFERENCES `PropositionVoter`.`Proposition` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
